# ===================================================================
# Netlify Proxy Yönlendirmesi
# ===================================================================

[[redirects]]
  from = "/api/*"
  to = "http://167.172.190.56:8000/:splat"

  status = 200

